# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sample',
            managers=[
                ('samples', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_treatment',
            field=models.CharField(default=600, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='system_composition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='system_id',
            field=models.CharField(max_length=6),
        ),
    ]
